package hx.domain.jpa;

// Generated 2013-3-12 21:29:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "test")
public class Role implements java.io.Serializable {

	private String id;
	private String name;
	private String value;

	public Role() {
	}

	public Role(String id) {
		this.id = id;
	}

	public Role(String id, String name, String value) {
		this.id = id;
		this.name = name;
		this.value = value;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
