package hx.domain.jpa;

// Generated 2013-3-12 21:29:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "test")
public class User implements java.io.Serializable {

	private String name;
	private String age;
	private String address;
	private String phone;
	private String email;

	public User() {
	}

	public User(String name) {
		this.name = name;
	}

	public User(String name, String age, String address, String phone,
			String email) {
		this.name = name;
		this.age = age;
		this.address = address;
		this.phone = phone;
		this.email = email;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 246)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age", length = 246)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "address", length = 246)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 246)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 246)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
