package hx.domain.hibernate;

// Generated 2013-3-14 19:59:23 by Hibernate Tools 3.4.0.CR1

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private String id;
	private String name;
	private String value;

	public Role() {
	}

	public Role(String id) {
		this.id = id;
	}

	public Role(String id, String name, String value) {
		this.id = id;
		this.name = name;
		this.value = value;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
