package hx.domain.hibernate;

// Generated 2013-3-14 19:59:23 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String name;
	private String age;
	private String address;
	private String phone;
	private String email;

	public User() {
	}

	public User(String name) {
		this.name = name;
	}

	public User(String name, String age, String address, String phone,
			String email) {
		this.name = name;
		this.age = age;
		this.address = address;
		this.phone = phone;
		this.email = email;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
